database:
  host: "localhost"
  databasePort: 5432
  databaseName: "product"
  userName: "productuser"
  password: "product"

migration:
  host: "localhost"
  databasePort: 5432
  databaseName: "product"
  userName: "productuser"
  password: "product"

server:
  port: 8080
  gracefullShutdownTimeout: 30