version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge